name: Trigger documentation update in p5.js-website

on:
  release:
    types: [published]

jobs:
  trigger:
    runs-on: ubuntu-latest
    name: Dispatch event to p5.js-website 
    steps:
      - name: Clone repository
        uses: actions/checkout@v1
      - name: Dispatch event to p5.js-website
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.P5JS_TOKEN }}
          repository: processing/p5.js-website
          event-type: p5.js-release
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'